### ISSUE TITLE
switchboard-plug-about crashed:  _tmp8_ = 0x4100000000 <error: Cannot access memory at address 0x4100000000

### ISSUE THREAD

**Issue by slackernetuk** [pimvullers/elementary#229]
Hiya guys, I know this repo is just for Gentoo, but possibly you could help. I also posted this issue on official switchboard-plug-about repo, but unfortunately I got no respond at all.  Slackware is possibly the reason why, they don't respond.....but is just a guess.

**What Happened?**
switchboard-plug-about plug crashed immediately

```
#0  0x00007ffff71de051 in __strlen_avx2 () at /lib64/libc.so.6
#1  0x00007fffec919aed in about_hardware_view_get_host_name (self=0x4e2450 [AboutHardwareView])
    at ../src/Views/HardwareView.vala:532
        _tmp0_ = 0xa08540
        hostname = 0x0
        _tmp3_ = 0xa08540
        _tmp4_ = 0x0
        _tmp5_ = 0x0
        _tmp6_ = 0x0
        _tmp7_ = 0
        _tmp8_ = 14591792
        result = 0x0
        __func__ = "about_hardware_view_get_host_name"
#2  0x00007fffec919f41 in about_hardware_view_constructor
    (type=0xda7cb0 [AboutHardwareView/GtkGrid/GtkContainer/GtkWidget/GInitiallyUnowned], n_construct_properties=0, construct_properties=0x0) at ../src/Views/HardwareView.vala:52
        obj = 0x4e2450 [AboutHardwareView]
        parent_class = 0x7ee030
        self = 0x4e2450 [AboutHardwareView]
        _tmp0_ = 0x788830 [GraniteSettings]
        _tmp1_ = 0x788830 [GraniteSettings]
        product_name_info = 0x0
        _tmp2_ = 0x52 <error: Cannot access memory at address 0x52>
        _tmp3_ = 0x7ffff7244300 <main_arena+1856> "\360B$\367\377\177"
        _tmp4_ = 0x0
        _tmp5_ = 0x430
        _tmp6_ = 0x0
        _tmp7_ = 0x7
        processor_info = 0x0
        _tmp8_ = 0x4100000000 <error: Cannot access memory at address 0x4100000000>
        _tmp9_ = 0x0
        memory_info = 0x0
        _tmp10_ = 0x7ffff7243c20 <main_arena+96> "\360", <incomplete sequence \341>
        _tmp11_ = 0xde9bf0 ""
        _tmp12_ = 0x0
        _tmp13_ = 0x0
        _tmp14_ = 0x7ffff70fbce4
        _tmp15_ = 0x0
        _tmp16_ = 0x0
        _tmp17_ = 0x0
        _tmp18_ = 0x430
        _tmp19_ = 0x44
        _tmp20_ = 0x0
        details_grid = 0x0
        _tmp21_ = 0x0
        _tmp22_ = 0x0
        _tmp49_ = 0x7ffff7fdc990
        _tmp50_ = 0x47b930
        _tmp51_ = 0x7ffff7eabb10
        _tmp52_ = 0x1
        _tmp53_ = 0x0
        _tmp54_ = 0x7fffffffd3e0
        _tmp55_ = 0x7fffec92d2b8
        _tmp56_ = 0xaee0f0
        _tmp57_ = 0
        _tmp63_ = 0x6dfe00
        _tmp64_ = 0x7fffec8fc100
        _tmp65_ = 0xd86c00 [GtkLabel]
#3  0x00007ffff7c35a75 in g_object_new_with_custom_constructor (n_params=0, params=0x0, class=0xde9c00)
    at ../gobject/gobject.c:1857
        cparams = 0x0
        cvalues = 0x0
        node = 0x0
        i = 0
        nqueue = 0x0
        newly_constructed = <optimized out>
        object = <optimized out>
        n_cparams = 0
        cvals_used = 0
        nqueue = 0x0
        object = <optimized out>
        __func__ = "g_object_new_internal"
#4  g_object_new_internal (class=class@entry=0xde9c00, params=params@entry=0x0, n_params=n_params@entry=0)
    at ../gobject/gobject.c:1937
        nqueue = 0x0
        object = <optimized out>
        __func__ = "g_object_new_internal"
#5  0x00007ffff7c36c0d in g_object_new_with_properties
    (object_type=0xda7cb0 [AboutHardwareView/GtkGrid/GtkContainer/GtkWidget/GInitiallyUnowned], n_properties=0, names=names@entry=0x0, values=values@entry=0x0) at ../gobject/gobject.c:2108
        class = 0xde9c00
        unref_class = 0xde9c00
        object = <optimized out>
        __func__ = "g_object_new_with_properties"
#6  0x00007ffff7c37531 in g_object_new (object_type=<optimized out>, first_property_name=<optimized out>)
    at ../gobject/gobject.c:1779
        object = <optimized out>
        var_args = 
            {{gp_offset = 0, fp_offset = 0, overflow_arg_area = 0x425ad0, reg_save_area = 0x7ffff7eb5551 <g_malloc0+33>}}
```
**Full backstrace**
[switchboard-plug-about-bt.txt](https://github.com/pimvullers/elementary/files/10047782/switchboard-plug-about-bt.txt)

**Comment by pimvullers** [comment]
Sorry, indeed this repo is only for Gentoo packaging, cannot support in this topic.
